### ISSUE TITLE
add gmail-specific hints when the user tries to create an gmail-account 

### ISSUE THREAD

**Issue by r10s** [deltachat/deltachat-android-ii#1]
see the old telegram ui, https://github.com/deltachat/deltachat-android/blob/master/MessengerProj/src/main/res/values/strings.xml#L325

**Comment by Boehrsi** [comment]
I already added that logic in https://github.com/deltachat/deltachat-android-ii/blob/master/src/org/thoughtcrime/securesms/RegistrationActivity.java#L113 but we can think about a more prominent way to tell the user the special handling of GMail.

**Comment by Boehrsi** [comment]
Fixed by https://github.com/deltachat/deltachat-android-ii/commit/ea5522f789c663c6f367f2673bf052d85a50f504

Also some cleanup stuff.
