### ISSUE TITLE
call "markseen" on messages scrolled into view

### ISSUE THREAD

**Issue by r10s** [deltachat/deltachat-android-ii#100]
DcContext.markseenMsgs() should be called for messages _really_ shown to the user.

calling this function will result in sending a read receipt, if requested by the sender.

**Comment by Boehrsi** [comment]
I try to get this one working.

**Comment by r10s** [comment]
cool - i would test this with a second device or so.

**Comment by Boehrsi** [comment]
@r10s due to sickness I will look into this starting on Monday and not today. Sorry for the delay.

**Comment by r10s** [comment]
@Boehrsi get well soon :)

**Comment by Boehrsi** [comment]
Should be ready on Friday. 👍

**Comment by r10s** [comment]
cool :)

**Comment by Boehrsi** [comment]
@r10s this should work now :)

**Comment by r10s** [comment]
cool :)

**Comment by r10s** [comment]
there is one superfluous markseenCall(), i will remove this, re-opening this issue until done.

**Comment by r10s** [comment]
> there is one superfluous markseenMsgs() call that marks a whole chat as beeing seen. i will remove this, re-opening this issue until done.

this is fixed.

however, in fact, not for all messages shown markseenMsgs() is called. eg. if there are 10 new messages, and the chat is opened and displays 3 of them, only for the last one markseenMsgs() is called.
scrolling up to the 7 other messages, will mark the first new on view as seen, for the other messages, markseenMsgs() is not called (maybe when entering the chat again, however)

**Comment by Boehrsi** [comment]
Hmm, makes sense, we should probably take all messages between findFirstCompletelyVisibleItemPosition and findLastCompletelyVisibleItemPosition.

**Comment by Boehrsi** [comment]
I will have a look tomorrow if time allows. I probably missed that case while testing due to the "constructed test case" I used (sent 3-4 messages to an account and scrolled down).

**Comment by r10s** [comment]
cool :)
well, it was easy to miss things as virtually all messages in the thread were marked as seen on opening the chat :)

**Comment by r10s** [comment]
@Boehrsi played around a bit, this is my solution: https://github.com/deltachat/deltachat-android-ii/commit/34597a086ea5507542d7f8cd4240c7c042004678 - is this fine from you point of view?

however, what should be improved: the sending should be delayed by a second or so to not disturb scrolling.

**Comment by Boehrsi** [comment]
@r10s looked into both commits and tested a bit. Looks good I would say. :)
The only thing we can consider is collecting the message ids first and only calling dcContext.markseenMsgs(ids) once. This way we could reduce the JNI call count. I created a branch for that https://github.com/deltachat/deltachat-android-ii/commit/a63cd2746b28c3d1452fa0b11f81e8d078b15472

**Comment by r10s** [comment]
thanks for checking :)
and yes, the optimized jni calls make sense :)
