### ISSUE TITLE
allow unblocking contacts

### ISSUE THREAD

**Issue by r10s** [deltachat/deltachat-android-ii#101]
contacts may be blocked by answering "never" in the contact request's quesion "Chat with NAME?"

so, we need an method to _unblock_ contacts.

- there is already an item at settings / privacy
- the corresponding activity show the list of blocked contacts (get be retrieved with DcContext.getBlockedContacts()
- a click on a blocked contact should ask "Unblock contact?"
- if so, the contact can be unblocked via DcContext.blockContact(contactId, 0)

**Comment by Boehrsi** [comment]
Will tackle that one.

**Comment by r10s** [comment]
great :)

will you re-use the "normal" contact list that is shown when clicking the "+" button? ContactSelectionActivity iirc or the corresponding fragment or at least the list items?

that would be great as i think we do want to have big things to maintain for the un-blocking stuff :)

**Comment by Boehrsi** [comment]
There is already something in place and in general I will try to reuse as much stuff as possible. Totally agree that this area shouldn't introduce much "extra stuff". _(Sorry for the late answer)_

**Comment by r10s** [comment]
the list looks good so far.

some nitpicking:
- it should _not_ be multi-selectable (or it should work, but it think this is not worth the effort)
- the dialog "unblock" button is labeled "block"

btw. you can test the blocking by sending a delta-chat messages from another account (if it is already in use, delete the chat) and answer the contact-request question with "never".

we should make the "block contact" function in the profile work to allow easier testing.

**Comment by Boehrsi** [comment]
Okay, I will adjust the mentioned points. Multi select was already explicitly disabled as far as I remember but I will have a look.

**Comment by Boehrsi** [comment]
Will probably finish that one on Monday, due to an unplanned home office day I wasn't able to accomplish much today.

**Comment by Boehrsi** [comment]
`
- it should not be multi-selectable (or it should work, but it think this is not worth the effort)
- the dialog "unblock" button is labeled "block"
- unblocking does not work, the contact is just not unblocked
`
Fixed
`we should make the "block contact" function in the profile work to allow easier testing.`
Added. Contacts can now be blocked using the "profile view" of a contact. Blocking does the following:

- Hide open chats
- Hide the contact in the contact list
- Add the contact to the blocked list, where the user can unblock contacts

**Comment by Boehrsi** [comment]
@r10s everything should work now, including the blocking part. :)

**Comment by r10s** [comment]
cool - will check this out later :)

**Comment by r10s** [comment]
cool, works like a charme :)
