### ISSUE TITLE
crash when creating a new group

### ISSUE THREAD

**Issue by r10s** [deltachat/deltachat-android-ii#103]
just a normal group with one member and without an avatar -> crash

**Comment by Boehrsi** [comment]
Strange I'm pretty sure I tried that one, will look into that right now.

**Comment by Boehrsi** [comment]
Next time I should try to "clean up not so much". Just removed a null check to much. Sorry. Fixed.

**Comment by r10s** [comment]
just wanted to come back to fix this and noticed it is already done :)
thanks :)
