### ISSUE TITLE
forward event from ApplicationDcContext to RegistrationActivity

### ISSUE THREAD

**Issue by r10s** [deltachat/deltachat-android-ii#11]
after calling ApplicationDcContext.configure() from RegistrationActivity the configuration is done (and working!) in the core that posts some events to the ApplicationDcContext.handleEvent() callback.

- the events may come from any thread, so Util.runOnMain() will probably be needed
- the events sent are DC_EVENT_CONFIGURE_PROGRESS with 0=error, <1000=progressInPermille, 1000=success, see [source](https://github.com/deltachat/deltachat-android-ii/blob/master/src/org/thoughtcrime/securesms/connect/ApplicationDcContext.java#L219)
- we may want to update the dialog opened in RegistrationActivity when receiving these events

@Boehrsi @angelo-fuchs => what is a graceful way to do so? 

probably, we will need to forward events also under other circumstances, eg. if a message is read, sent, new messages are received [and so on](https://deltachat.github.io/api/group__DC__EVENT.html).

**Comment by Boehrsi** [comment]
If I get it right this would be a component like the _NotificationCenter class + listeners_ in the old code? I liked the general approach used there.
In my opinion we should use something similar:

- The core feeds a central DcMessageCenter if an event occurs
- The events are separated by types (e.g. configure, message received, message sent etc.) and returned values are mapped there (e.g. to listener calls with onStart(value), onProgress(value), onSuccess(value),  onError(value))
- Every instance interested in certain events registers to a specific type in the DcMessageCenter
- The DcMessageCenter controls the list of listeners (public add / public remove / private notify)
- Every class interested in callbacks needs to implement a listener interface and the DcMessageCenter only accepts those classes
- If an object / class is not interested anymore it should unregister itself as a listener
- To avoid to much boiler plate code we can introduce Base* elements which provide some core listener features used often

**Comment by r10s** [comment]
> if I get it right this would be a component like the NotificationCenter class + listeners in the old code?

- yes, this would work, i also found the concept of listeners rather smart.
i just wanted to make sure not just to copy "bad" copy from telegram without asking an android expert :)
- to avoid boiler-plated code, maybe we could just forward the raw events. having eventId+data at the correct places looks sufficient to me
- i would add all this to the signal-part, not to the com.b44t.messenger - which is independent from Android currently
- wondering, how signal handles this, maybe we can use things from there

**Comment by Boehrsi** [comment]
@r10s you are welcome :)

> to avoid boiler-plated code, maybe we could just forward the raw events. having eventId+data at the correct places looks sufficient to me

But that would mean implementing the handling at different places (possibly in different ways, which could be good, but could also lead to Spaghetti Code) and also multiple times. This can be countered by Base* classes but that wouldn't work always. 
In that case I would prefer a more centralized solution which provides some sort of abstraction. At least the registering and delegation based on types should be done there in my opinion.

> i would add all this to the signal-part, not to the com.b44t.messenger - which is independent from Android currently

That's true but I hoped that we could keep this closer to the core bindings, as this not Android specific but I would say kind of core bindings specific. Regardless of the UI we would always use this event delegation component.

**Comment by r10s** [comment]
> At least the registering and delegation based on types should be done there in my opinion.

@Boehrsi not sure if we're talking about the same :)

from the view of the event consumer, i am thinking about sth. like
```
class MyActivity implements NotificationCenter.Delegate
{
  onCreate() {
    NotificationCenter.addObserver(DC_EVENT_MSGS_CHANGED);
  }

  onDestroy() {
    NotificationCenter.removeObserver(DC_EVENT_MSGS_CHANGED);
  }
  
  @Override
  public void handleEvent(int event, int data1, int data2)
  {
  }
}
```

the main reason is that i can very easily add new events this way by just adding the ID to DcContext.

> That's true but I hoped that we could keep this closer to the core bindings

we'll it depends on if the core binding should be java or java-android. we already have a subfolder "connect" - maybe we can add the signal-android-core specific things there? we can also rename the folder to "core-bindings" or so, see #7 
however, i have no really strong opinion on this, we can also move it to com.b44t.messenger.

**Comment by r10s** [comment]
@Boehrsi but maybe this is too c-ish, not sure :)

**Comment by Boehrsi** [comment]
@r10s ah okay I think i misunderstood you. I like the above approach and if we see we have to duplicate code we can still add some helper classes / methods somewhere. But please lets ditch the  NotificationCenter naming ;), as Notifications have a pretty specific meaning in the Android context.

Regarding the location of that code I have also no strong opinion, it`s more a feeling that we should put that nearer to the core. But we can just try out how everything works. Btw. I think that part could also be used by normal Java code, not only Android.

**Comment by ralphtheninja** [comment]
`EventCenter` :)

**Comment by r10s** [comment]
> Btw. I think that part could also be used by normal Java code, not only Android.

that would be perfect and that is a strong argument to put it to com.b44t.messenger

> EventCenter :)

:)

or more boring, DcEventDispatcher ?

**Comment by Boehrsi** [comment]
Both fine ;) or a combination DcEventCenter.

**Comment by r10s** [comment]
i would vote for DcEventCenter, the Dc prefix makes sense when it belongs to com.b44t.messenger
