### ISSUE TITLE
cant See Massage buttons in dark disign

### ISSUE THREAD

**Issue by happyreacer** [deltachat/deltachat-android-ii#110]
In the dark design cant see the icons for a audiomessage, attachements and cliparts or smileys.
I think there are need  more contrast ;-)

**Comment by r10s** [comment]
hi @happyreacer thank you for your post.

i think this is a duplicate of https://github.com/deltachat/deltachat-android-ii/issues/50#issuecomment-431658734

feel free to comment there or to re-open this issue if you meant something else :)

**Comment by happyreacer** [comment]
Ah thank you. It is a duplicate.
