### ISSUE TITLE
unlocking does not work

### ISSUE THREAD

**Issue by r10s** [deltachat/deltachat-android-ii#112]
when enabling "Settings / screen lock", and Delta gets locked, there is no possibility to unlock it and go to the chatlist, chat or whatever. instead the unlock screen is shown over and over.

this has worked some time ago, see #42, and the bug was probably introduced by some other changes.

@Boehrsi i think you know the related code best - maybe you can have a look at his?

**Comment by Boehrsi** [comment]
Strange, will have a look tomorrow as today we have Holiday ☺ and i'm not at my PC right now.

**Comment by r10s** [comment]
@Boehrsi cool - and have some nice holidays :)

**Comment by Boehrsi** [comment]
Should work again @r10s

**Comment by r10s** [comment]
@Boehrsi yeah, works again for me :)
