### ISSUE TITLE
verified-icon not always visible in chat-titlebar

### ISSUE THREAD

**Issue by r10s** [deltachat/deltachat-android-ii#120]
if the name of the group gets a bit longer, the verified-icon is "moved away" from the chat-titebar.

EDIT: ~~in the chatlist, the verified-icon is fine.~~ nope, it's also cutted there.

what is the easiest way to force this being visible? while keeping a simple, floating layout?
cc @Boehrsi

**Comment by r10s** [comment]
for which are setCompoundDrawables() used currently?
at least on the right, there should be nothing.

sugestion:
- title-left: group-icon
- title-right: verified icon
- subtitle-left or excerpt-left: mute-icon

did i forget anything?
at least for now, this should fix the problem easily.

**Comment by Boehrsi** [comment]
I think blocked and archived are also located somewhere, but using setCompoundDrawables() and just put the icons beside the title and the subtitle sound like a good solution. I will have a look.

**Comment by r10s** [comment]
they might come from signal, however, in delta:
- "blocked" is not really needed normally - the chats and contacts are just not shown. 
- and "archived" is shown beside the delivery-state-icons which is also fine and no problem as there is no text that could get wider and move things away.

**Comment by r10s** [comment]
@Boehrsi great :) just tested, lgtm :)
