### ISSUE TITLE
Forward from RegistrationActivitiy to ConversationList

### ISSUE THREAD

**Issue by angelo-fuchs** [deltachat/deltachat-android-ii#13]
When the Registration is complete we should go to the conversation list.

**Comment by Boehrsi** [comment]
The automatic "back to WelcomeActivity / RegisterActivity" mentioned in the IRC should get fixed by my changes in https://github.com/deltachat/deltachat-android-ii/issues/10

**Comment by r10s** [comment]
great, meanwhile we also have the DcEventCenter (#11) nice too see things growing :)
