### ISSUE TITLE
make imap_folder configurable

### ISSUE THREAD

**Issue by r10s** [deltachat/deltachat-android-ii#132]
i think there should be an option in the advanced settings, below imap-sever and smtp-server options. just an input field that takes the IMAP-folder-name, see [imap_folder](https://c.delta.chat/classdc__context__t.html#aff3b894f6cfca46cab5248fdffdf083d)

**Comment by webratte** [comment]
I would like to test DC (dev version) with a special Deltachat folder.

So it would be graet if you could add this option in the next release.

Thank you

**Comment by r10s** [comment]
closing this until https://github.com/deltachat/deltachat-core/issues/422 is solved; it's not really clear which ui option will be there in the end.
