### ISSUE TITLE
Importing system contacts seems broken

### ISSUE THREAD

**Issue by Boehrsi** [deltachat/deltachat-android-ii#134]
It seems like the importing of system contacts into Delta Chat Core (implemented in https://github.com/deltachat/deltachat-android-ii/issues/46) is not working anymore on the latest master.

**Situation:**

- After granting the permission to load the contacts no contacts are added / shown

**Expected:**

- After granting the permission to load the contacts the system contacts are added / shown

@r10s is currently verifying if this issue also affected him or if this is a local problem of @Boehrsi.

**Comment by r10s** [comment]
i can confirm that it does not work for me as well :)

**Comment by Boehrsi** [comment]
Will tackle that one on Friday.

**Comment by Boehrsi** [comment]
@ralphtheninja tests are generally possible but everything involving the AndroidTest part makes it significantly complexer. But I will have a look.

**Comment by Boehrsi** [comment]
Will probably finish that one on Monday, due to an unplanned home office day I wasn't able to accomplish much today.

**Comment by Boehrsi** [comment]
@ralphtheninja totally get your point there ;) and totally agree with you that we should start testing. I will just have a look if it is possible without unreasonably high effort and if so I will just do it :).

**Comment by Boehrsi** [comment]
Fixed by the mentioned commit (just removed the unneeded permission). I wrote a reminder for myself to recheck the testing stuff, but for now I would say it's a bit too much effort. @r10s can you also verify that it's working again?

**Comment by r10s** [comment]
@Boehrsi why does it fail when _too many_ rights are requested?

**Comment by r10s** [comment]
apart from that, yes, it's working again.

but i really would like to understand why :)

**Comment by Boehrsi** [comment]
@r10s The app needs to define all permissions it will ever ask for in the manifest and we removed the write permission for contacts, as we don't need it. But that means the request for "read and write" permissions, which was performed right before importing the contacts just always failed, as the write permission was never granted. That blocked the importing process.
