### ISSUE TITLE
Add preference / settings functionality

### ISSUE THREAD

**Issue by Boehrsi** [deltachat/deltachat-android-ii#14]
After login the user is unable to open the settings. The app crashes as we have no address object, which is needed. To avoid a crash and provide the needed functionality we should adjust the ProfilePreference.java and other needed classes to display DeltaChat releated user information.

- [x] Avoid crash on entering settings screen
- [x] Avoid crash on entering account settings screen and enable the adjustment of account settings
- [x] Allow enabling / disabling of app locking, see #42 for more information 
- [x] Add security check to backup and key export
- [x] Remove Settings / Notifications / Calls category

**Comment by Boehrsi** [comment]
First iteration added (https://github.com/deltachat/deltachat-android-ii/commit/1b1d20f53be659c4e912ae1ae82c5dff292e847b), which avoids the initial crash and gets the first config values via core.

**Comment by Boehrsi** [comment]
I will now adjust the edit profile part, which is currently also crashing, as it references the address object mentioned in https://github.com/deltachat/deltachat-android-ii/issues/17.

**Comment by Boehrsi** [comment]
Added https://github.com/deltachat/deltachat-android-ii/commit/75971f7320d970d95afcbe655a80e2447b964792 to allow the user to change the name and the avatar image within the settings. The settings are applied and used now.

**Comment by r10s** [comment]
great :)

my suggestions:
- i would open a local Alert instead of an URL when clicking on "Who can see this information?"
- i would add a "back arrow" button to the action bar, esp. as the normal. the arrow can have the same effect as "set later".
- maybe we can add an additional button "password and account settings" below "set later" and open the RegistrationActivity from there (to re-configure the account)

**Comment by Boehrsi** [comment]
Cleaned up the "Privacy" setting fragment

- removed REGISTRATION_LOCK_PREF as we have no phone number registration
- removed ALWAYS_RELAY_CALLS_PREF as we don't have calls and even if we would support calls we don't want to relay them using specific servers
- added an information toast if the "Screen security" setting is changed. As the user needs to restart the app before this setting will be active

Changed / added the suggested adjustments:
> great :)
> 
> my suggestions:
> 
>     * i would open a local Alert instead of an URL when clicking on "Who can see this information?"
> 
>     * i would add a "back arrow" button to the action bar, esp. as the normal. the arrow can have the same effect as "set later".
> 
>     * maybe we can add an additional button "password and account settings" below "set later" and open the RegistrationActivity from there (to re-configure the account)
The mentioned optimizations were implemented. For the "who can see this" stuff I wrote a short sentence which can get adjusted later if needed.

**Comment by Boehrsi** [comment]
https://github.com/deltachat/deltachat-android-ii/commit/08a4e63ea411d091e95777feaca8c1ca408947e5

**Comment by Boehrsi** [comment]
Commit: https://github.com/deltachat/deltachat-android-ii/commit/8ad1652cc6e4f7c98342a5132cdb2c333e32f6df

- added an information toast if the "Screen security" setting is changed. As the user needs to restart the app before this setting will be active

**Comment by r10s** [comment]
cool :)

i think the credentials in the RegistrationActivity should be pre-filled with the current settings - incl. the password so that the user can click reconfigure without doing changes (not that this is always useful, however, people will do so :)

**Comment by Boehrsi** [comment]
Added prefill for RegistrationActivity

**Comment by Boehrsi** [comment]
Will gather potential other tasks in the preferences area tomorrow and will add them as sub tasks to this ticket.

**Comment by Boehrsi** [comment]
@r10s I added "Remove 'Settings / Notifications / Calls' category" as task. Is this a good idea for now or should it stay in the settings?

**Comment by r10s** [comment]
no, we can remove them. 
i also cleaned up the chats activity yesterday.

**Comment by Boehrsi** [comment]
Added the security check to the backup and key export.

**Comment by r10s** [comment]
great :)

**Comment by Boehrsi** [comment]
Removed Settings / Notifications / Calls category. I would say the main part of the settings is now working as intended and we should close this issue for now. Other problems with the preferences could be tackled in newly created tickets. What's you opinion about this @r10s ?

**Comment by r10s** [comment]
also removed "contact-joined-deltachat", see #67, closing this now :)
