### ISSUE TITLE
Add a way to get rid of red backgrounds

### ISSUE THREAD

**Issue by gerroon** [deltachat/deltachat-android-ii#141]
Hi

Can you please add a way to disable or get rid of the red tinted message reply backgrounds. Some contacts seems to be choosen as red so their messages have red background, but that makes it look like everything they say have some importance or emergency.

Editing the contact color does not work.

thanks

**Comment by r10s** [comment]
@gerroon thank you for your post. i am also not 100% happy with the colors, however, due to other more pressing issues, it was a bit delayed.

the formally postponed and now re-opened issue is #51 - as this one is a it broader, i would suggest to continue the discussion there and close this one.
