### ISSUE TITLE
Replies are in Inbox

### ISSUE THREAD

**Issue by gerroon** [deltachat/deltachat-android-ii#142]
Hi

My replies to an existing chat is delivered to the inbox instead o designated folder

LineageOS 14.1

v0.0.9

The previous DC release from Fdroid does not have this issue. I think I am going to go back to Fdroid version, this is too annoying to be honest :(

**Comment by r10s** [comment]
hi @gerroon thank you for your post.

> My replies to an existing chat is delivered to the inbox instead o designated folder

yes, this is the _current_ default behavior. the core already allows to use a different folder than the INBOX, however android-dev is still missing an option for it, however, it is planned, see #132 

the general single-folder approach is discussed in the mailing list (some reasons are user-expectations and multi-device support) and an option to get back the old behavior is discussed in https://github.com/deltachat/deltachat-core/issues/422

**Comment by gerroon** [comment]
Ok thanks for the informative reply

**Comment by r10s** [comment]
@gerroon you're welcome
