### ISSUE TITLE
implement "attach contact"

### ISSUE THREAD

**Issue by r10s** [deltachat/deltachat-android-ii#148]
attaching a contact to a chat should show the contact list, let the user select one and set the text field just to 
```
Name
user@example.org
```
it's up to the user to modify the text and to send it then.

**Comment by Boehrsi** [comment]
I will look into that one on Friday.

**Comment by Boehrsi** [comment]
Should work now.

**Comment by r10s** [comment]
great, the predefined text in the draft is exactly as expected :)

for the list as such, this is still the system address book as before. however, i would suggest to use the delta contact list instead:
-  includes all email addresses that are in the system contact book
- _plus_ the one that are in delta only
- it works also if the user rejected rights to the address book

sorry for having been unclear here :)

**Comment by Boehrsi** [comment]
Ah okay, didn't get the in the first run. Will adjust that.

**Comment by r10s** [comment]
great :)

**Comment by Boehrsi** [comment]
Should be fixed now, adjusted our BlockContactsActivity and renamed it to be able to cover both areas without introducing too much new code.

**Comment by r10s** [comment]
much better, thank you very much.

however, i would still try to use the normal delta contact list as this would provide a search and also these sticky letters on the left look nice.

maybe we could also use the normal delta contact list for the blocked contacts and for the group member list (which still looks ugly)

but i would not regard this as a top-priority so it is probably okay to close this issue.

**Comment by r10s** [comment]
opened subsequent issue in #162
