### ISSUE TITLE
remove giphy

### ISSUE THREAD

**Issue by r10s** [deltachat/deltachat-android-ii#149]
giphy as a centralized service is not on pair with the overall goal of decentralization.

if would be glad, however, to have a functionality to serach eg. images and gif in user-defined search engines, which, of course, can be predefined then. but this is another issue, just want to mention this is someone want to take care  :)

**Comment by Boehrsi** [comment]
Will take care of this. I will remove the Giphy calls and I will hide the GIF entry for now. I will keep as much of the logic part as possible, so a later re-implementation wouldn't be that hart.

**Comment by r10s** [comment]
well, i would not take care too much of things that may happen on this in the future. i would throw away the icon in the attachment bar (however this is easily possible, the result are 7 then) and remove after that all classes that are unused.
in general, we do not want as few code as possible, i think these sort of functions are rather easy to add afterwards if needed - and the code is not gone :)

**Comment by Boehrsi** [comment]
Fixed.

**Comment by r10s** [comment]
great - what a fun to remove code ;)
