### ISSUE TITLE
remove notification about making Delta Chat the default SMS-app

### ISSUE THREAD

**Issue by r10s** [deltachat/deltachat-android-ii#15]
at least for now (we can leave the code :)

**Comment by Boehrsi** [comment]
Will do that one today (including the settings part, where this should also get removed).

**Comment by Boehrsi** [comment]
Fixed by https://github.com/deltachat/deltachat-android-ii/commit/3e72e2f6c83f02c3cedb4b177d5ddc92cdfad45f
