### ISSUE TITLE
make video playback work

### ISSUE THREAD

**Issue by r10s** [deltachat/deltachat-android-ii#152]
at least on my device, the video playback is not started.

~~i think for now, we should handle video playback just as normal files - start the intent that is responsible for videos, no need for an internal player imho, the telegram-ui did just the same.~~

~~in some 2.0 version we can create preview images for videos (and record videos!), however, even then i would prefer using the system player for playback.~~

EDIT: i think, we shoud just go for the exoplayer, while checking the database stuff, i came across MediaView and it seems to be just a matter of using the correct file. 
this also gives us the option to handle videos later as images (swipe ...). and also from a security perspective, it may be interesting to play back videos only internally.
moreover, the exoplayer may help on recoding, so that it is needed anyway.

**Comment by angelo-fuchs** [comment]
I just sent a .mkv Video to my delta. The attachment in the mail is marked as 'video/x-matroska' 

```
--MP_/P9vSrvsRaZJ0QLceYv30hgm
Content-Type: video/x-matroska
Content-Transfer-Encoding: base64
Content-Disposition: attachment; filename=vokoscreen-2018-09-29_18-32-10.mkv
```

But when the Action Intent is called, `DcMsg.getFilemime()` returns `application/octet-stream`.
Same goes for text messages.

**Comment by r10s** [comment]
updated my mind: i think we should stay with the internal player, see my edit in the first post.
