### ISSUE TITLE
show the extension beside the size of attachments

### ISSUE THREAD

**Issue by r10s** [deltachat/deltachat-android-ii#153]
currently, attachments are displayed as 

```
file name.ext
1.2 MB
```

if the file name is longer, it may be truncated and it is unclear of what type the attachment is.

as a simple fix i would suggest to add the extension in upper case characters beside the size:

```
the last information before traveling starts-2018-11-01.pdf
1.2 MB PDF
```

**Comment by r10s** [comment]
just noticed that the extension for _some_ file types is shown in the icon beside the name, at least for PDF but _not_ for EPUB. 

showing the extension there is probably even smarter than my proposal, however, at least extensions with 4 characters should be shown as well.

**Comment by Boehrsi** [comment]
Should work now.
