### ISSUE TITLE
logo in '/artwork' folder needed?

### ISSUE THREAD

**Issue by r10s** [deltachat/deltachat-android-ii#154]
there is a logo in the 'artwork' folder at https://github.com/deltachat/deltachat-android-ii/blob/master/artwork/logo-512.png - of course we can replace it with the delta chat logo, however, i have no idea for what this logo is used. playstore? or can it be removed?

maybe @Boehrsi or @angelo-fuchs knows more :)

**Comment by angelo-fuchs** [comment]
I don't see any place its referenced. I grepped through the code, etc. and did not find anything.
Its almost certainly safe to remove, I will do so.

**Comment by r10s** [comment]
cool :)
