### ISSUE TITLE
Add a UI item to change DC folder

### ISSUE THREAD

**Issue by webratte** [deltachat/deltachat-android-ii#159]
Since DC dev version uses "whatch a single folder".
So I need a UI item to configure a folder which should handled as DC inbox. (e.g. inbox/deltachat)

I would like to see this feature in the near future 😀

**Comment by r10s** [comment]
we can think this over when https://github.com/deltachat/deltachat-core/issues/422 is done.

however, it is better to discuss feature requests with a broader audience in the forum at https://support.delta.chat

**Comment by webratte** [comment]
I believe feature requests posted in the forum will lost in the bottom of the forum very fast 😉
And you know this.

A issue in github will stay as open until its fixed or marked as "will not fixed" and its always visible and so it will be not forgotten.

But it's your project and your rules and so I opened a new topic in the forum:

https://support.delta.chat/t/add-a-way-to-set-user-defined-dc-folder/165

**Comment by r10s** [comment]
@webratte thank you very much :)

however, i do not think that discussions in the forum get lost if there is some interest on a topic.

in fact, we'll tend to close discussions and feature requests that no one is working on _here_, but _not in the forum_ :)
