### ISSUE TITLE
[Feature Request] Dark mode

### ISSUE THREAD

**Issue by Rubylion** [deltachat/deltachat-android-ii#160]
A dark mode would be very pleasant. thx

**Comment by r10s** [comment]
hi @Rubylion - thank you for your post.

in fact, the current android-dev version (more info at https://delta.chat/en/2018-10-12-android-dev) actually has a dark mode at settings / appearance / theme

**Comment by Rubylion** [comment]
great. thx

**Comment by r10s** [comment]
@Rubylion yes, but it is not totally clear when. probably this year :)
