### ISSUE TITLE
make contact name editable

### ISSUE THREAD

**Issue by r10s** [deltachat/deltachat-android-ii#166]
there should be an option in the contact's profile

**Comment by violoncelloch** [comment]
Do we really need this? Isn't it easier and simpler to just use the name from the system address book? (as e.g. Whatsapp does it)

**Comment by r10s** [comment]
we want to be independent from the address book. 
not all contacts in delta chat are in the system address book.

**Comment by violoncelloch** [comment]
Ok, then it makes sense! Thank you for clarifying
