### ISSUE TITLE
Adjust or remove address object 

### ISSUE THREAD

**Issue by Boehrsi** [deltachat/deltachat-android-ii#17]
Signal provides an address object, which is used all over the app. It contains information about a user or group and is used for various things (e.g. also mapping of avatar images and so on). 
We have do decide if we want to keep that object and use it as wrapper for our data delivered by the Delta core or do we want to remove that object as a whole and replace the calls within the app with the direct calls to the core.
I think @angelo-fuchs already did a lot of stuff there, so we probably already have some insights.

In general I would like to keep the address object and "just" adjust the logic (removing all that parcerable stuff and other unneeded things). We could just keep it as container for the calls to the DcHelper. This would minimize the footprint of our changes and would probably increase the maintainability.

**Comment by r10s** [comment]
i would also try to keep the address object.
otherwise we would produce code that is no more working, i think this is something we should avoid.

**Comment by r10s** [comment]
Beside the Address object, i think it is also useful to keep some other objects.
Eg. the ThreadRecord that is needed for the ConversationList items, but also for other things.

For now, i put the helper function to ApplicationDcContext, see
https://github.com/deltachat/deltachat-android-ii/commit/71bd8c3903ff93a56bb03ebc9a9d3484a57640a1#diff-bba88278bbbbe5532b9e7dfa9294bbe0R95, which makes some sense, however, it it gets to crowded there, we can also use a separate class for this object factoring.

I think, in general, the objects that contain only dump data and no functionality are good candidates to leave; this was also one outcome of @angelo-fuchs researches iirc :)
