### ISSUE TITLE
remove language_name from strings.xml

### ISSUE THREAD

**Issue by adbenitez** [deltachat/deltachat-android-ii#177]
res/values/strings.xml::language_name:
After checking the file directly I realized (reading the comment) this string must be the current language, but what translators seems to be doing is simply translating the word "English" to they language, perhaps it isn't obvious for translators using transifex, what is the real meaning of this string.

**Comment by r10s** [comment]
well, we've added a hint, however, in fact, the string is not directly needed for android.
it is only needed to copy+paste the language name to the internal popup.

maybe we can just get rid of it instead of trying to explain complicated things ...

**Comment by adbenitez** [comment]
Well this is an static thing, perhaps can be done automatically

**Comment by r10s** [comment]
yip, `language_name` obviously causes too much confusion, we also had question on irc to this.

i think it should be just removed.
