### ISSUE TITLE
Voice message player not working properly 

### ISSUE THREAD

**Issue by adbenitez** [deltachat/deltachat-android-ii#182]
The voice message player doesn't work as expected: the "progress bar" doesn't work, doesn't move while the message is reproduced, also can't start to reproduce from... lets say the middle of the message.

- Platform (android/blackberry/anbox): Andorid 6.0
- Device: BLU
- Delta Chat Version: 0.91 and 0.92

**Comment by adbenitez** [comment]
IMPORTANT: 
just checked and this is happening with the old voice messages (.ogg) alos to add that volume isn't working with this audio messages.
The messages recorded with v0.92 don't have any of this issues

**Comment by r10s** [comment]
okay, i see. this is of minor importance then.
in general, it's not really clear which audio-format we will pick, see https://github.com/deltachat/deltachat-android-ii/issues/172#issuecomment-447130466

for now, the most important thing is that it words delta-dev to delta-dev.

**Comment by r10s** [comment]
closing this in favor of #172
