### ISSUE TITLE
delay requesting rights to the time they are really needed?

### ISSUE THREAD

**Issue by r10s** [deltachat/deltachat-android-ii#19]
i would suggest to delay requesting-of-rights to the time these rights are really needed.

i have the feeling that this is more clear to the user what is happening then.

eg. i would suggest to remove requesting the rights to access WRITE_CONTACTS, READ_CONTACTS from RegistrationActicity to the opening of the contact list (we would only need READ_CONTACTS btw).

WRITE_EXTERNAL_STORAGE and READ_EXTERNAL_STORAGE can also be moved. READ_EXTERNAL_STORAGE is needed when a backup should be importet and when the gallery should be accessed (afaik).

**Comment by Boehrsi** [comment]
Makes sense, just kept it because the Signal logic performed it that way. 
But requesting the permissions at runtime, during the interaction which really requires the permission, is definitely the correct approach.

**Comment by r10s** [comment]
perfect :)

**Comment by r10s** [comment]
i think, the question is answered, todo-issue in #68, together with some permossion-cleanup
