### ISSUE TITLE
always scroll down on message sending

### ISSUE THREAD

**Issue by r10s** [deltachat/deltachat-android-ii#209]
when sending a message, the chat view should always scroll down to the lower border of the new message sent.

this is not always the case, eg. when forwarding a message to a chat, no scrolling takes place. in other situations, a message is only half visible.

EDIT: simple reproducible by sending an image in portrait format, btw.

**Comment by violoncelloCH** [comment]
I'm not so sure about that. It's quite annoying if you want to reply on a series of messages and always have to scroll back up to read further...

**Comment by adbenitez** [comment]
I don't like it :P 
I usually have several messages on a group for example, I read an reply every message, if users wants to go to the bottom, there are a button for that, so it is more annoying to scroll up every time I reply a message than simply tapping the go to bottom button when I need it.

**Comment by adbenitez** [comment]
well this shows us that what is a bug for someone is a feature to someone else ;)
I really gonna miss this bug, but you are right about the state of the messages
