### ISSUE TITLE
Double mark shown but not all group members had read the message

### ISSUE THREAD

**Issue by adbenitez** [deltachat/deltachat-android-ii#211]
As shown in the screenshot, I have created a group with 6 members, I have sent a message and it is marked as read (double mark icon) but only 3 of the 5 other members had received it. Is this a bug or the expected behavior??

- Platform (android/blackberry/anbox): Android 6.0
- Device: BLU
- Delta Chat Version: 0.97.1
- Expected behavior: double mark is shown when all members had read the message
- Actual behavior: double mark is shown when an arbitrary amount of members had read the message
- Steps to reproduce the problem: not easily reproducible
- Screenshots:
![screenshot_20190105-132426](https://user-images.githubusercontent.com/24558636/50847609-0c7f1300-1340-11e9-8c85-1b3294048cff.png)

**Comment by r10s** [comment]
> Is this a bug or the expected behavior??

it's the expected behaviour, see https://delta.chat/en/2017-07-06-read-receipts-and-social-pressure for some background.

**Comment by adbenitez** [comment]
After reading the link I think it makes sense

**Comment by r10s** [comment]
thanks for thinking about it :)

**Comment by adbenitez** [comment]
After thinking a bit about this, this is a bit confusing for users, I was thinking all group members had received the message when saw the double check mark, a better approach would be to show "n VIEWS" where n is the number of members that have read the message, this way users know that not all members had read the message, this will not force the users having this disabled to do enable it, and the user sending the message can known how many users had read the message, avoiding the confusion of the double mark

**Comment by adbenitez** [comment]
> interesting but i think a number here is not neccessarily helpful.

how it is showing a double mark more helpful?? at leas with a number I know how many members have seen the message, I can know if at least 1 or 2 members had read the message or if the 90% had read it, with a double mark the first thing a users think is that **all** members had received the message, also if I don't see a double mark I don't know if at least 1 or X members received it, showing a number may not be "the killer feature" but it is much more useful than showing a double mark, which actually cause misunderstanding. 

> What do you do if you read "14 views" in a 22 member group

what do I do if I see a double mark??? seeing 14 views and after a while seeing 20 views at least is more useful than always seen a double mark after 22/2 members had seen the message, at least I easily know if more users had read the message.



> Maybe it's more interesting to have in "message details" a precise list/visualization of who send read-notification and who didn't.

well that would be awesome +1 I just asked for something more simple to avoid asking for complex features that perhaps you guys don't want to implement right now :)

**Comment by hpk42** [comment]
so let's maybe see to inform about who sent read notifications in
"message details" and then use that for a while.  Not immeidately sure
how much effort this is but probably more than estimated ;) 

P.S.: you are probably aware that folks typically have a lot of things 
to read and process, various channels, github notifications, chats, 
emails, or RL discussions so brevity on gh issues is usually appreciated. 
there also is IRC or private chats which require less brevity discipline ;)

**Comment by r10s** [comment]
> Maybe it's more interesting to have in "message details" a precise list/visualization of who send read-notification and who didn't.

it's already there: long click message -> info (just a simple text, but, anyway :)

**Comment by adbenitez** [comment]
> so let's maybe see to inform about who sent read notifications in "message details" and then use that for a while. Not immeidately sure how much effort this is but probably more than estimated ;)

I am already doing this, the info menu does this for the selected message, but it is too much work for each message, and the dialog is a bit hard to read, and feels really a hack for a normal user, check it in the image I shared on the first post of this issue.

> P.S.: you are probably aware that folks typically have a lot of things to read and process, various channels, github notifications, chats, emails, or RL discussions so brevity on gh issues is usually appreciated.

sorry about that, `--verbose` option removed ;)

**Comment by r10s** [comment]
sure, the dialog can be polished at a given time, just wanted to point out the the information, if a concrete member has read a post, is already available.

**Comment by adbenitez** [comment]
@hpk42 I was thinking you was talking about something similar to the way riot handles this...
so an user that has read receipt disabled is just like an IRC user in riot

**Comment by adbenitez** [comment]
> sure, the dialog can be polished at a given time, just wanted to point out the the information, if a concrete member has read a post, is already available.

yeah this information is useful, that is why I think it would be awesome to make it more accessible to the users, and this is really possible to make it without affecting users that don't want to use this feature, using it in a more direct way like riot does makes feel DC more in "real time" and more easy to know if users are online

**Comment by r10s** [comment]
well, i personally do not like the way riot shows the read state and i also do not like too many numbers (i do not think they're useful) and/or information directly beside a message :)

**Comment by adbenitez** [comment]
well, then the only thing I can say is that showing a double mark on groups will be confusing, and users will have to go to the info option, which involves: long tapping a message, tapping  the info option, carefully reading this dialog to find the info they want and tap "OK", I am following this routine for every message I send in a group, and even several times for the same message to check if other people had read it since my last check, Obviously this is a pain :(

**Comment by r10s** [comment]
> well, then the only thing I can say is that showing a double mark on groups will be confusing

not sure about that.
the double-check-marks are well known from other messengers (whatsapp, telegram and signal among them), also for groups.
so, we're just re-using know ux patterns.

**Comment by adbenitez** [comment]
> but, the double-check-marks are known to show that _all_ users have read/recieved a message

exactly this has happened to me I was thinking this was a bug on DC!!!

**Comment by r10s** [comment]
the meaning of the double-check-marks in groups differs in detail between different apps, so, not sure what _all_ user would expect :)

**Comment by adbenitez** [comment]
sorry to been a dork and keep with this talk but, what is the point then on using this pattern if it is not know for the same purpose in all apps??? then it is better to use a patter that cause just 0 confusion :P

**Comment by adbenitez** [comment]
> not sure what _all_ user would expect :)

if we are not sure what all users would expect, and on top of that we do no do exactly what other apps do, how can we expect users will "guess" the behavior of the double mark on DC???

**Comment by r10s** [comment]
first of all, thank you for taking care. this is very much appreciated.

> if we are not sure what all users would expect

i think we can never be sure on this point ;)

>  and on top of that we do no do exactly what other apps do, how can we expect users will "guess" the behavior of the double mark on DC???

this "exactly" is just not available, and differs eg. between whatsapp and telegram.

but i think it is still unique enough and known to the user as _a double check mark means sth. as "read by recipient/group"_

i think this is still easier to explain as an eye with a number or mini-avatars (at least to me they are also not obvious)
i am not saying that these pattern do not make sense at, however, they may not be more intuitive to users. and they also have their disadvantages the user has to be aware of, what @hpk42 pointed out above.

**Comment by adbenitez** [comment]
> this "exactly" is just not available, and differs eg. between whatsapp and telegram.

so, double mark is not an standard, and we are using it just for yet another meaning

> but i think it is still unique enough and known to the user as _a double check mark means sth. as "read by recipient/group"_

but that is NOT for what Delta Chat use it, since double mark appears when not all the group members had read it, from my point of view you are doing something like using just green and red for traffic light, with an overlapping between them...  accidents coming soon ;)

> i think this is still easier to explain as an eye with a number or mini-avatars (at least to me they are also not obvious)

perhaps I am just a weird person, but from my point of view an eye with a number of view have no need to be explained at all, it is self explanatory! and I think it is a common pattern also, users just know an eye icon with a number means number of views, I am not inventing the more cool feature of ever, this is something already used, actually I was aware of the "views" pattern before knowing about this "double mark" pattern that I just discovered now with Delta Chat, for 1x1 chats it is ok but for groups it just don't work. 
Also have to say that mini-avatars like Riot does are much more self explanatory than your double mark implementation I just know what they do by looking it working, I had to read a whole article to understand how double mark works on Delta Chat!!! that is just wrong!!! :/


>  they may not be more intuitive to users

I don't think so at all :) the current double mark behaviour is much more complex and less intuitive!!!




> and they also have their disadvantages the user has to be aware of, what @hpk42 pointed out above.

what disadvantage??? what @hpk42 said: "What do you do if you read "14 views" in a 22 member group?" well it is much more useful to see "14 views" from 22 than seen a double mark that means "half or more had read this" 
and when he said: "And those who once skimmed new messages in a chat (one of the 14) might actually totally have overread the important information" that is not really a disadvantage at all, if we take this in consideration then we should say "lets remove the read receipt feature altogether because some users may not read the message and 'might actually totally have overread the important information' " so I don't see any disadvantage yet, while I do see disadvantages in the current implementation of the double-mark pattern on DC

again, sorry the long reply :)

**Comment by hpk42** [comment]
this issue is closed and i think several things have been repeated already.  Closing does not mean that the behaviour will never change but the current discussion is exhausted.  I am pretty sure we are going to revisit the issue at one point or another but let's not ride this dead horse (ie closed issue) much more now.
