### ISSUE TITLE
Tell which user added/removed another user to a group

### ISSUE THREAD

**Issue by hpk42** [deltachat/deltachat-android-ii#215]
i've run several times into the situation that i had no idea who a newly added member was -- "Member dideldi@dumbledum.net" added -- this degrades the feeling/association i can feel with that group, as it turns more "unknown" progressively.  

As a first measure, how about saying "X added/removed member Y to/from group".

A second measure could be to also display the "adder" (if known) in the "member edit" view with each contact or so.

**Comment by r10s** [comment]
yip, this should be improved. was thinking about sth. as "Y added by X", however :)

i think there is a related issue for this in the core already, mainly wrt to show the text in the language of the receiver, not the sender, however, i cannot find it currently :)

**Comment by r10s** [comment]
this is the missing link: https://github.com/deltachat/deltachat-core/issues/220 (status messages should be shown in the language of the receiver)

**Comment by hpk42** [comment]
OK but i think even without #220 it makes sense to add the semantic info
who added/deleted whom, in the sender's language.  In many cases, people
in a group will speak the same language anyway.
