### ISSUE TITLE
use lower bitrate for aac voice-messages

### ISSUE THREAD

**Issue by r10s** [deltachat/deltachat-android-ii#218]
we should use sth. comparable-in-size to the f-droid-version, see https://github.com/deltachat/deltachat-android-ii/issues/172#issuecomment-451418674 for some more information.

- 0.20 tg-f-droid-version using ogg-opus@16kbit: 150K (telegram-standard)
- 0.97 android-dev-version using aac-opus@32kbit: 260K (signal-standard)
- 0.97 android-dev-version using aac-opus@24kbit: 198K <-- some artefacts hearable on my device
- 0.97 android-dev-version using aac-opus@16kbit: 130K <-- many artefacts hearable on my device

however, my test-microphone is also bad, so, not representative.
i think we should pick a test sound file and convert it to the three options above with audacity or so and take this as the base for decisions.

**Comment by r10s** [comment]
okay, skipping theoretical tests for now. 

i've decreased the aac bitrate from 32kbits to 24kbits, theoretically, this should be roughly the same quality as ogg-opus with 16kbits (or aac-he, which, however, [does not work on all systems](https://stackoverflow.com/questions/26504386/mediacodec-audio-video-muxing-issues-ond-android))

it's now slightly larger than the f-droid-ogg-opus, however, more compatible (also due to other  optimisations, voice-messages are no longer uploaded twice and then downloaded once, so, overall, it is still much better :)

**Comment by hpk42** [comment]
very cool -- eager to try this out :)

**Comment by adbenitez** [comment]
Me too =)
