### ISSUE TITLE
update logo and branding

### ISSUE THREAD

**Issue by r10s** [deltachat/deltachat-android-ii#22]
- [x] replace logo+name in the title bar of the ConversationList by just the string "Delta Chat" (just as in the current app).
having the colored logo there will look choppy imo.
also we will have a 3rd icon beside "search" and "menu" for qr ocde scanning, adding also the logo there may make the title bar too crowded.
- [x] update app name
- [x] update app logo - i think we should just use the same icon as for the old app
- [x] search for "Signal" in strings and replace them by "Delta Chat"
- [x] credit Signal in README explicitly
- [ ] write "dev" or so on logo

EDIT: during development, we use the app name "Delta Chat dev", we switch it later to "Delta Chat" then.

**Comment by r10s** [comment]
belonging commits, https://github.com/deltachat/deltachat-android-ii/commit/1cbfab14147ce5645fc354375af13501b8d75405,  https://github.com/deltachat/deltachat-android-ii/commit/e9df8aaf409386f1b12fdea956e359d1d1ca9ec8

**Comment by angelo-fuchs** [comment]
I think it might be better to have an altered logo (with a little σ in the upper right corner) to indicate the new codebase, at least as long as we have both apps installed side-by-side.

**Comment by r10s** [comment]
or maybe just a new app name as "Delta Chat II"

**Comment by hpk42** [comment]
On Fri, Sep 14, 2018 at 03:52 -0700, björn petersen wrote:
> or maybe just a new app name as "Delta Chat II"

Delta Chat dev? 

Let's maybe avoid trying to have "signal" too much in user facing things. 
We could also reuse this concept for future "breaking" changes.
With delta-chat export / delta-chat-dev import one could directly
start using it, right?

**Comment by r10s** [comment]
> With delta-chat export / delta-chat-dev import one could directly start using it, right?

yes.

**Comment by angelo-fuchs** [comment]
Just renaming it does the job from my perspective. I just happen to like hidden clues.

I slightly prefer "Delta Chat Dev" over "Delta Chat II" (as it avoids questions like: When will Delta Chat II be available on Platform X).

**Comment by hpk42** [comment]
think it's nice to have a hint in the logo (just "dev" written over it or so)

**Comment by r10s** [comment]
@hpk42 here you are:

![dev-logo](https://raw.githubusercontent.com/deltachat/deltachat-android-ii/3fe51ceab882be661c443672e8a48e36579a6eba/res/mipmap-xxhdpi/ic_launcher_dev.png)
