### ISSUE TITLE
new chat background

### ISSUE THREAD

**Issue by violoncelloCH** [deltachat/deltachat-android-ii#222]
Hi @r10s
I would like to create a new (default) chat background for deltachat. Something that connects to the name and fits into the design of the rest of the application...
What would be the desired format and ratio for the background? Could you point me to the current file? I only found the one used in desktop (https://github.com/deltachat/deltachat-desktop/blob/master/images/background_hd.jpg).

**Comment by r10s** [comment]
it's the same in android: https://github.com/deltachat/deltachat-android-ii/blob/master/res/drawable-xhdpi/background_hd.jpg

**Comment by violoncelloCH** [comment]
thank you :) I just didn't find it and a github search for `background_hd` didn't return anything...
do you have any requirements / expectations for a new background?

**Comment by r10s** [comment]
to be honest, i have not really thought about much this before.

the current background has a shade that is optimized to the darkness of the bubbles (left: light bubbles->lighter background, right: darker bubbles->darker background). also the background should not distract reading/visibility too much and work together with the delta-title color (blue-green-sth).

apart from that: i think, it would be great if you shift this discussion to the forum for a larger audience and also platform-independency. and, of course, we cannot promise that a suggestion becomes the new default  - but i am rather curious :)

**Comment by r10s** [comment]
closing as the initial question is answered, looking forward to see proposal at https://support.delta.chat/ then :)
