### ISSUE TITLE
use ok/cancel for adding members

### ISSUE THREAD

**Issue by r10s** [deltachat/deltachat-android-ii#224]
currently, the adding-members-activity shows the "back" button in the title-bar to confirm the selected members.

it should better have the "cancel" and "ok" button-symbols in the title-bar.

**Comment by hpk42** [comment]
On Fri, Jan 11, 2019 at 15:28 -0800, Asiel Díaz Benítez wrote:
> +1 
> As an user, I was a bit confused by this, was thinking that the back button would cancel all

+1, same here -- the current member adding flow is slightly irritating.
