### ISSUE TITLE
use ok/cancel for the login screen

### ISSUE THREAD

**Issue by r10s** [deltachat/deltachat-android-ii#225]
currently, the login-screen shows the a login-button below the input fields. this is a but unusual and also the keyboard often lies over the button. 

it should better have the standard "cancel" and "ok" button-symbols in the title-bar.

moreover, i would add the "for known ..." text below the email/password fields and above the advanced-button.

**Comment by florianhaar** [comment]
will change this today

**Comment by r10s** [comment]
cool :)

**Comment by florianhaar** [comment]
Done. I hope that it is ok :)

**Comment by r10s** [comment]
@florianhaar great, much better. 

some nitpicking: i would clean up the code a bit and make the "For known email providers text" left-aligned.

in general, as just discussed on irc, i would like to got for a pr based routine in the future. this makes it possible to discuss such changes before merging to master - and also delay merging to master a bit eg. if there is a release upcoming and the changes are no urgent bug fixed (but have the potential to introduce new ones :)

**Comment by r10s** [comment]
@violoncelloCH thanks for taking care. is this locking a github feature? 

however, i do not think this is needed as all ppl with access to the repo are informed. and i do not want to break already started flows that do not use pr. also, there might be reasons not to use prs ("bump version" an so on)

**Comment by violoncelloCH** [comment]
@r10s yes, that's a Github feature... can be found in repository Settings > Branches > Branch protection rules
of course, this would need PRs for bumping the version too (except you leave direct write access for administrators open)... But it ensures that nobody (by accident) can do wrong things to the master branch. And you could even enforce automatic tests to pass before PRs can be merged...

**Comment by r10s** [comment]
@violoncelloCH thanks for explanation, didn't know this feature exist at all.
