### ISSUE TITLE
allow to send chat with delta chat when clicking on a mail link in an other app

### ISSUE THREAD

**Issue by violoncelloCH** [deltachat/deltachat-android-ii#235]
with deltachat telegram ui it's possible to chat with a person after clicking on a email `mailto:` link in any other app (e.g. in a browser).
this should be possible with the new ui as well
- Delta Chat Version: v0.98.2

**Comment by Boehrsi** [comment]
Will look into that today.

**Comment by r10s** [comment]
great :)

**Comment by Boehrsi** [comment]
Should work now as requested.

**Comment by r10s** [comment]
works great - and makes so much sense, thank you very much :)
