### ISSUE TITLE
Allow to import a Backup after login

### ISSUE THREAD

**Issue by angelo-fuchs** [deltachat/deltachat-android-ii#243]
The 0.20 version allowed for a backup import from the advanced settings / backup area. The 0.98 version does not.

I'd like to have that function back.

**Comment by r10s** [comment]
nope. also 0.20 did not allow it.
the menu entry just shows a hint that say "reinstall to import".

**Comment by angelo-fuchs** [comment]
@r10s Does the core allow to delete all my data?

**Comment by r10s** [comment]
@angelo-fuchs no. however, this would be just the deletion from the database plus the folder.

in general, it is not impossible to allow importing a backup, however, it needs testing and so on. it's also a bit tricky with the threads (there android-threads are currently just never stopped eg.), all in all, it's some work and i do not think its the most important thing to do currently :)

**Comment by angelo-fuchs** [comment]
@r10s I understand and agree.

**Comment by angelo-fuchs** [comment]
But as an afterthought: We might want to add the message that to import a backup one needs to deinstall and reinstall as it was in 0.20

**Comment by r10s** [comment]
yes, this would make sense.

**Comment by adbenitez** [comment]
Just want to say that importing/exporting is important for people that need to manually sync with imports to avoid the unwanted sync operation, if you don't allow users to disable syncing, and they have to reinstall to import the backup every time they use another client, this will be **really** bad :(

**Comment by angelo-fuchs** [comment]
@adbenitez I did not understand the use case. Why would somebody sync with import?

**Comment by adbenitez** [comment]
To avoid to sync from server because is slow and the real reason: costs money!!

**Comment by angelo-fuchs** [comment]
@adbenitez So they deinstall the app to stop it?
