### ISSUE TITLE
Infoboxes look weird

### ISSUE THREAD

**Issue by angelo-fuchs** [deltachat/deltachat-android-ii#248]
- Modell: FP1U
- Android-Version: 4.2.2 (Jelly Bean)
- Kernel: 3.4.5
- API Version: 17

Upon displaying info boxes (see the example below, but happens for other situations as well) there is a gray background (good) then a white rectangle (confusing) then the actual infobox with dropshadow (good).

This white rectangle around the infobox should not be there, instead the infobox should place its shadow directly above the gray background.

I suspect that this is caused (in part) by the old android version I have.

![screenshot_2019-01-18-14-03-38](https://user-images.githubusercontent.com/10619521/51388581-30a1d780-1b2a-11e9-98e9-d8597475e1a0.png)

**Comment by angelo-fuchs** [comment]
I just noticed that on contact-requests, the question "Do you want to start a chat with ..." looks normal.

**Comment by Boehrsi** [comment]
I will have a quick look :+1:

**Comment by r10s** [comment]
great :)
ony my devices, the boxes look fine, however, might be that some use an additional view or so instead just a text.

**Comment by Boehrsi** [comment]
Found the problem, it's a wrong import for dialogs:

-  import android.support.v7.app.AlertDialog vs the currently used import android.app.AlertDialog

Those older Android versions require the support libraries. I will adjust the imports across the app.

**Comment by Boehrsi** [comment]
Found another one: 
ProgressDialog has the same problem, but there is no android.support version of it. So I started the implementation of a small CustomProgressDialog which is nearly done. Some small UI corrections on Monday and that should also work (without real changes in the current usage of progress dialogs).
