### ISSUE TITLE
make notifications work

### ISSUE THREAD

**Issue by r10s** [deltachat/deltachat-android-ii#32]
this is strongly related to https://github.com/deltachat/deltachat-android-ii/issues/8

- [x] have a notification at all
- [x] notification can mark as noticed so it goes away
- [x] swipe marks as notified
- [x] tapping on notification should open deltachat and navigate to chat (if single) or chatlist (if multiple)
- [x] tapping 'Answer' on notification opens the instant-answer overlay
- [x] sound
- [ ] vibration
- [x] proper icon & general look and feel
- [x] seems like notifications only working after app has been opened once...
- [ ] no notifications for a chat while its visible

**Comment by angelo-fuchs** [comment]
Open:
- [ ] tapping on notification should open deltachat and navigate to chat (if single) or chatlist (if multiple)
- [ ] tapping 'Answer' on notification opens the instant-answer overlay, but that is not working atm.

tbd: should swiping do anything?

**Comment by r10s** [comment]
> tbd: should swiping do anything?

i think swiping the notification shouldn't do anything but removing the notification from the list.
not 100% sure, but i think this was also the behavior on telegram-delta.

**Comment by angelo-fuchs** [comment]
> seems like notifications only working after app has been opened once...
So, it takes several minutes after a restart of my phone before the notification is displayed but it does.
If it actually start to bother users we should look deeper into this.

**Comment by r10s** [comment]
great progress, anyway :)

**Comment by angelo-fuchs** [comment]
vibration would most likely work if the relevant parts of user profile were already ported to DC.

**Comment by r10s** [comment]
great - and, in fact, the "Reply" button below the notification seems to be _very_ useful :)
have not thought that.
