### ISSUE TITLE
add option to delete contacts

### ISSUE THREAD

**Issue by r10s** [deltachat/deltachat-android-ii#37]
the contacts in delta chat are more suggestion for e-mail addresses to create chats.
contacts that are in used by chats, cannot be deleted (they can be blocked).

however, sometimes the user wants to delete an contact from the list explictly, eg. he may have added it accidentially, a typo or whataever.

i would suggest to offer such an option via a long-click on a contact in the contact list.
the option should appear in the action bar as a trash bin then (same as for chats or messages)

**Comment by Boehrsi** [comment]
Starting with this issue today.

**Comment by r10s** [comment]
cool :)
it it is not too much additional effort, a multi-select-delete would be great :)

**Comment by hpk42** [comment]
On Thu, Oct 04, 2018 at 02:01 -0700, björn petersen wrote:
> cool :)
> it it is not too much additional effort, a multi-select-delete would be great :)

indeed, a general techqniue for multi-select would be great, eg 
multi-select chats and archive/delete ... multi-select messages
and delete etc.

**Comment by r10s** [comment]
> multi-select chats and archive/delete ... multi-select messages and delete etc.

these boths are already available in android-dev :)

**Comment by r10s** [comment]
@Boehrsi cool - cu tomorrow :)

**Comment by Boehrsi** [comment]
Added as requested.

**Comment by r10s** [comment]
cool - will check this out asap :)

**Comment by r10s** [comment]
@Boehrsi great job :) 

esp. the "select all" followed by a delete which is sort of a cleanup, as contacts that are in use are not deleted at all (cc @Ampli-fier, i think this was one of your wishes some time ago :)

some nitpicking:

- when any contact is long-pressed, the items "new group" and "new verified group" are grayed out - i think the idea is to show that they cannot be selected. however, i think they _look_ selected this way. i would not change the appearance of these values at all.  
same for the "new contact", if it is there.
you can find out these "special" IDs by checking for `id <= DC_CONTACT_ID_LAST_SPECIAL`  everything larger than DC_CONTACT_ID_LAST_SPECIAL is selectable and can be deleted if unused.

- maybe related: some times, when playing around, the "new group" stays selected. eg. by long-clicking a real contact, clicking "select all" and pressing the system "back" button (not: the action bar back-button). after that "new contact" is selected although not being in selection-mode.

**Comment by Ampli-fier** [comment]
> cc @Ampli-fier, i think this was one of your wishes some time ago :)

Yes, right.

As I couldn't code this for the UI I created a [Core cmdline function](https://github.com/deltachat/deltachat-core/blob/79ab1600da6e938030fc5c0ee0798153e7465248/cmdline/cmdline.c#L82) that does the same.

Really great to have this finally in the UI :) :+1:

**Comment by Boehrsi** [comment]
@r10s happy to hear it's overall working as intended :). In regards to the small review request:

1. Graying out that "special values" was a bit of work, but removing that is totally no effort. The UI normally does nothing there and I thought adding something would be a good idea. But I think you are right, it does more or less the opposite of the intended.

2. Removing that gray background as request in 1. will fix that problem.

I will adjust / fix the mentioned points on Monday. :)

**Comment by r10s** [comment]
thanks, will have a look at this :)

**Comment by r10s** [comment]
@Boehrsi there is still a weird behavior on multi-selecting items:

- select the first contact (probably "A") -> select the _third_ contact -> deselect the third contact -> now, "New group" gets selected :)
- doing the same with the fourth entey results in a selected "New verified group"

moreover, having selected multiple contacts and clicking delete: this seems to delete only the first contact. i would suggest to add the deletion in a thread. also here, there is no need to redraw or so as DC_EVENT_CONTACTS_CHANGED are emitted on changes.

**Comment by Boehrsi** [comment]
https://github.com/deltachat/deltachat-android-ii/issues/46 and https://github.com/deltachat/deltachat-android-ii/issues/81 are fixing some of the problems. The strange highlighting issue remains. I will tackle the latter now.

**Comment by Boehrsi** [comment]
Should be fixed now. Finally. ;)

**Comment by r10s** [comment]
great. i added the deletion in a thread in https://github.com/deltachat/deltachat-android-ii/commit/179e8173c97cf2ae7da6ad65bf3c95d47c4bde5c - feel free to correct me if this is not good android/java style - i am no expert here :)

however, for now, this can be closed :)
