### ISSUE TITLE
Reintegrate core

### ISSUE THREAD

**Issue by Boehrsi** [deltachat/deltachat-android-ii#4]
We have to integrate the core to make the UI actually work. It was already done here [https://github.com/r10s/deltachat-android-ii/commits/master](https://github.com/r10s/deltachat-android-ii/commits/master) and should be done in a similar way for this project.
We just need to clarify the way the actual core library (jni/messenger-backend) should get integrated. Probably as a submodule or something similar?

**Comment by Boehrsi** [comment]
Just created a patch, based on the commits made in the other repo and did some small adjustments to the Android.mk file as the c build process failed due to wrong paths. The result is the following commit: https://github.com/deltachat/deltachat-android-ii/commit/de016eba2cb9b4070f7d260a663535e54604ce7e

**Comment by Boehrsi** [comment]
Fixed by https://github.com/deltachat/deltachat-android-ii/commit/c805aa8d64723151c142dd72bc70382f454e681f

Core added as submodule.

**Comment by r10s** [comment]
great :)
