### ISSUE TITLE
make application locking work

### ISSUE THREAD

**Issue by r10s** [deltachat/deltachat-android-ii#42]
signal application locking is done using the system credentials (pin, password, pattern, fingerprint)

currently, the function is disabled and the option in the settings as well (just because of crashes and other things being more important)

i think, this would be a nice feature and probably simple to implement as it should be mostly independent of deltachat-core

**Comment by Boehrsi** [comment]
Just prepared everything needed in the AppProtectionPreferenceFragment. Removed unneeded stuff and adjusted the security stuff regarding our requirements.
Will add the actual logic to lock the app on Monday.

**Comment by Boehrsi** [comment]
- Added locking for background to foreground switch (screen lock)
- Added timeout lock (inactivity timeout lock)
- Added configurable timeout interval

**Comment by Boehrsi** [comment]
Added some additional messages and allowed the usage of the timeout lock without enforcing the usage of background / foreground lock (screen lock).

**Comment by r10s** [comment]
@Boehrsi great, will test this now :)

**Comment by r10s** [comment]
@Boehrsi great that you push this forward, very good job :)

some nitpicking after a first test:

- the settings overview always shows "Screen lock on" in the summary (btw when working on this, also the "registration lock" should be removed) 
- i think the "Inactivity timeout lock" and "Inactivity timeout interval" should be disabled when the screen lock is disabled by the switch (they are already disabled when screen lock is disabled by the system)
- i would add a `<PreferenceCategory android:layout="@layout/preference_divider"/>` or so between "inactivity timeout interval" and "screen security" and title the first category maybe "Screen lock" and the new one "App access".
- i would move the "Change secret" to the end of the category (just below "Inactivity timeout interval") - this looks smarter if the controls are disabled (as the "Change secret" is never disabled and it is not that clear what is enabled/disabled by the  "Screen lock on" switch then

**Comment by Boehrsi** [comment]
Makes sense :), will tackle this adjustments tomorrow.

**Comment by r10s** [comment]
@Boehrsi implemented the "read receipts" in the same dialog, hopefully, nothing is broken.

wrt "registration lock" in the overview: maybe we can show the "read receipts" state beside the lock state there.

**Comment by Boehrsi** [comment]
https://github.com/deltachat/deltachat-android-ii/commit/7530bcd592568fb2769fc6ac91a170c7ea6af144

- Fixed the settings summary (now showing screen lock state and read receipts with correct values)
- Disabled "Inactivity timeout lock" if "screen lock" is disabled
- Added the requested preference category
- Moved change secret
- Small adjustment regarding yesterdays "screen lock" commit

**Comment by r10s** [comment]
cool, from my side this, issue can be closed :)

might be that we need a timeout _before_ the lock is shown (so that it is not that annoying if the app is in background for a few seconds @kermoshina), however i would wait for feedback on this point.
same for the interval-selector, maybe a menu with some predefines as "30 seconds - 1 minute - 5 minutes" is easier to handle, but i would also wait for feedback on this point. maybe it's fine as it is.

@Boehrsi one question to the "Inactivity timeout lock" - is it really inactivity? so, is the timeout reset when there is some activity as scrolling?

**Comment by Boehrsi** [comment]
@r10s Yep it is a "real inactivity" counter :). And regarding the timeout before a lock, that could be a good idea. But I would also say we could close this issue for now and wait for feedback regarding the actual user requirements.

**Comment by r10s** [comment]
> Yep it is a "real inactivity" counter :)

cool :)

okay, i close this issue, done so far :)
