### ISSUE TITLE
add contacts from the system address book to internal contact database

### ISSUE THREAD

**Issue by r10s** [deltachat/deltachat-android-ii#46]
each time the contact list is opened, the system address book should be read and all names+email addresses should be added using [`dc_add_address_book()`](https://deltachat.github.io/api/classdc__context__t.html#a4b5e52c5d45ee04923d61c37b9cb6498) resp. `DcContext.addAddressBook()`.

this should be done in a thread, currently, currently, it is not needed to remove addresses added; the contact list is more a text-completion tool than an fully-functional address book.

the old code is here:  https://github.com/deltachat/deltachat-android/blob/master/MessengerProj/src/main/java/com/b44t/messenger/ContactsActivity.java#L196

**Comment by Boehrsi** [comment]
Will look into that one next week. :+1:

**Comment by r10s** [comment]
great - maybe we can also have little a/v next week.
have a nice weekend in between :)

**Comment by Boehrsi** [comment]
Added the requested changes.

**Comment by r10s** [comment]
great :)

as mentioned, however, there is a funny screen appearing under some circumstances (see attached image).

- the screen appear to me for some seconds the first time the contacts are read. 
- on subsequent opening of the contact list, it flashes only shortly
- when access to the contact are denied, it appears permanently with the button

![image](https://user-images.githubusercontent.com/9800740/46619195-d1dbc380-cb21-11e8-927f-9edf9b9669a4.png)

**Comment by Boehrsi** [comment]
Okay, I will adjust this today. @r10s would you ping me if the core update is ready? Thanks. :)

**Comment by r10s** [comment]
@Boehrsi updated, `DcContext.addAddressBook()` results in a DC_EVENT_CONTACTS_CHANGED event which is already handled in the activity.

**Comment by Boehrsi** [comment]
Great will integrate this now :).

**Comment by Boehrsi** [comment]
Adjusted the loading in regards to the updated core and removed the "loading screen". If the user grants the permission the address book is loaded + delta contacts and if not, just the available delta contacts are loaded from the core. The user is ask for permission when entering the contact screen.

**Comment by r10s** [comment]
great - also that the permission can be denied and the app just uses the internal contacts then.

i think this issue can be closed :)
