### ISSUE TITLE
style the member list on the group-creation activity

### ISSUE THREAD

**Issue by r10s** [deltachat/deltachat-android-ii#48]
the add-group-activity should probably also display the avatars of the selected members and use a proper margin; maybe the best is to use the normal ContactSelectionListItem

**Comment by r10s** [comment]
also SELF should be shown in the member list, at least when editing groups, not sure for group-creation.

**Comment by Boehrsi** [comment]
@r10s is this one still valid? The add group part contains avatars now and for editing the /me reference is also there. I would say the latest adjustments fixed this ticket also.

**Comment by r10s** [comment]
> Or do you mean the initial screen which shows the already selected members with the "X" on the right?

yes, this is what i was talking about, but i think for now we should close this, there is more important stuff to do :)

**Comment by r10s** [comment]
re-opened as a broader issue in #162
