### ISSUE TITLE
use a different applicationId

### ISSUE THREAD

**Issue by r10s** [deltachat/deltachat-android-ii#5]
we should use a different applicationId and make the applicationId independent from the package names 

at least during bootstrapping the id should be different from com.b44t.messenger (current Delta F-Droid app) and org.thoughtcrime.securesms (Signal), so that all three apps can be installed on the same device.

maybe we can use chat.delta.android-ii during bootstrapping.

@Boehrsi i tried to change it, however, i go lots of errors (i do _not_ want to change the package name (they should remain as org.thoughtcrime.securesms), maybe you have an idea here.

**Comment by Boehrsi** [comment]
Will add that tomorrow.

**Comment by Boehrsi** [comment]
Set to **chat.delta.androidii** as _chat.delta.android-ii_ is not allowed ("-" is a forbidden char).

Fixed by 516929071c3b9bdfa3dc8c69f373bce63bdd9681

**Comment by r10s** [comment]
not sure what i was doing wrong, but i _think_ i tried the same without success :) you have magic hands :)

**Comment by Boehrsi** [comment]
;) sometimes that little green robot needs a clean build or similar to accept his fortune. ;)

**Comment by r10s** [comment]
"nach dem boot wird alles gut"  
_- wisdom i got from an older programmer when in youth years :)_
