### ISSUE TITLE
Mark all Read must be undoable or disabable

### ISSUE THREAD

**Issue by angelo-fuchs** [deltachat/deltachat-android-ii#53]
I accidentally tapped 'mark all read' because I wanted 'new chat'. Then all the info was lost.

So we need to either repeat the question ('are you sure') or move the button somewhere where you can't accidentally click it or add an option (e.G. in settings) to disable this feature.

**Comment by r10s** [comment]
"are you sure" messages might be hated by users, however, in this case, this seems to be the easiest solution.

**Comment by hpk42** [comment]
On Wed, Sep 26, 2018 at 03:02 -0700, björn petersen wrote:
> "are you sure" messages might be hated by users, however, in this case, this seems to be the easiest solution.

one UX metaphor here is "undo" which allows one to not ask annoying questions.  
But that's probably a large impl change.

**Comment by r10s** [comment]
> But that's probably a large impl change.

might be. the code on ui-side is there and used eg. for archiving/unarchiving.
so dc_marknoticed_all_chats() could return an array of message-ids which can then be given to dc_markfresh_msgs() (which, unfortunately, does not exist yet).

**Comment by r10s** [comment]
thinking it over, i am not even sure this function is needed/helpful at all.
- it was not there in the old ui
- it is not available in whatsapp/telegram
- it was never requested by a delta chat user
- the function makes it very easy for the user to miss a message
- as mentioned above, it has its flaws
- there is alrady an "archive all" available that works with the existing ui elements - but makes it clearer to the user what happens as everything is really selected
- in general, i am skeptical with new ui elements :)

so, i would suggest to disable the function at all for now and close this issue.
we can come back later here if there is some need for such a function.

**Comment by hpk42** [comment]
@r10s so you mean that "mark all read" is not needed and can be removed, right?  

i am fine with removing it for now, and closing this issue.

**Comment by r10s** [comment]
> so you mean that "mark all read" is not needed and can be removed, right?

yes :)
