### ISSUE TITLE
remove .so files from repository

### ISSUE THREAD

**Issue by r10s** [deltachat/deltachat-android-ii#6]
i would suggest to remove the [`.so`](https://github.com/deltachat/deltachat-android-ii/tree/master/libs) files form the repository (add `.so` to `.gitignore`). in contrast to signal, these binaries get a reasonable size of several mb.

@Boehrsi @angelo-fuchs i think we all have ndk-build ready and at a give time the core-lib should go to maven anyway.

what do you think?

**Comment by r10s** [comment]
just did the change to avoid spamming of the repo, i leave this issue open for discussion (if needed)

**Comment by ralphtheninja** [comment]
@r10s You might want to consider pushing up this commit as the first commit, since the binaries are still in the git database.

**Comment by r10s** [comment]
@ralphtheninja do you know of this can be achieved by a `git rebase` or something similar?
however, it's only some mb of no more-growing-overhead, seems not to be that important :)

**Comment by ralphtheninja** [comment]
> @ralphtheninja do you know of this can be achieved by a git rebase or something similar?
> however, it's only some mb of no more-growing-overhead, seems not to be that important :)

I was thinking you could remove `.git` folder and make a `git init` again and force push that, since the commit history isn't _that_ long yet, in case you're worried about the commit history.

> it's only some mb of no more-growing-overhead, seems not to be that important

Aye, maybe not that important :) Still, like 10Mb that will hang in there forever :)

On the other hand, it's possible to _rewrite_ the git history using `git filter-branch`.

**Comment by r10s** [comment]
@ralphtheninja sounds interesting. so a ...
```
git filter-branch --tree-filter 'rm -rf libs/*/libnative-utils.so jni/cyrussasl/* jni/openssl/* jni/libiconv/*' HEAD
git push origin master --force
```
should do the job to delete old .so files and the unused c-libraries?

**Comment by ralphtheninja** [comment]
> in my local test, the .git folder is not smaller afterwards (not even after a git gc), however, the space may be reused anyway, not sure how the garbage collection in git works.

`git gc` in my experience is not enough, you should really try to re-clone the repo to see the effect, you can always try the clone locally

**Comment by ralphtheninja** [comment]
> ... should do the job to delete old .so files and the unused c-libraries from all commits?

Yes, the command looks correct. But I haven't used this git feature in a long time.

**Comment by r10s** [comment]
just executed the commands from above, the repo should be several mb smaller without the .so handing around in old commits
