### ISSUE TITLE
show "first message may take a while" in new chats

### ISSUE THREAD

**Issue by r10s** [deltachat/deltachat-android-ii#62]
in the old apk, we're using for normal chats

    <string name="NoMessagesHint">Send message to %1$s:\n\n• It is okay if %2$s does not use Delta Chat.\n\n• Delivering the first message may take a while.</string>

and for group chats:

    <string name="MsgNewGroupDraftHint">Compose the first message, allowing others to reply within this group.\n\n• It is okay if not all members use Delta Chat.\n\n• Delivering the first message may take a while.</string>

maybe we can combine this with a nice graphic as for the empty chat list, so a complete xml layout that is easily changeable later then.

**Comment by florianhaar** [comment]
will tackle this one tomorrow

**Comment by r10s** [comment]
great - for the image, maybe just copy+rename the one from the empty chatlist, i think the graphics will be reworked in all later on.

**Comment by florianhaar** [comment]
added the information in empty chats

**Comment by r10s** [comment]
@florianhaar great job :)

thinking it over, i also think that a graphic is not needed, esp. when it comes to customized backgrounds.

at a given point we should maybe tweak the background to be semi-transparent and use this background also for the dates and for the system messages (so that they do not interfere with custom backgrounds), but that's another issue that can be opened if really needed later.

**Comment by r10s** [comment]
just noticed that the background is already semi-transparent as the old app 
and fits perfectly with any background. very cool :)

![2018-10-empty-chat](https://user-images.githubusercontent.com/9800740/47240896-14d34c00-d3ea-11e8-9a02-0cc09a386392.png)
