### ISSUE TITLE
how preferences do work

### ISSUE THREAD

**Issue by r10s** [deltachat/deltachat-android-ii#64]
@Boehrsi just a, possibly stupid, question to get a better understanding about how the preferences work on android.

eg. for enable/disable the screen lock, we use `SCREEN_LOCK = "pref_android_screen_lock";` and access the setting everywhere in the code using `SCREEN_LOCK`.

that's clear to me :)

however, i do not find any line of code that initializes the corresponding control to the actual value. there is a `setScreenLockEnabled()`, which, however, is only executed when the control is `clicked`, not when AppProtectionPreferenceFragment is just loaded.

so, there seems to be some magic in one of the used preference classes?

if, so, i am wondering what we should do with preferences stored in the deltachat-core-database. it's fine if the preference class does its magic, however, we probably always want the controls to be initialized by the recent deltachat-core-value, not by a magic-shadow-setting (most times, however, they will be equal).

more concrete, i am wondering if this line https://github.com/deltachat/deltachat-android-ii/blob/master/src/org/thoughtcrime/securesms/preferences/AppProtectionPreferenceFragment.java#L147 shouln't better use the recent setting directly from deltachat-core, eg. as `dcContext.getConfigInt("mdns_enabled", DcContext.DC_PREF_DEFAULT_MDNS_ENABLED))`.

**Comment by Boehrsi** [comment]
The settings are directly connected with the shared preferences of Android by e.g. loading `addPreferencesFromResource(R.xml.preferences_app_protection);`. If we don't apply any custom handling for specific preferences the values are just get / set without any further need to implement anything.
This is truly kind of problematic in regards to "external settings" like our core settings. Starting with Android 8.0 there is a https://developer.android.com/reference/android/preference/PreferenceDataStore which allows a different data source, but Android 8.0 is obviously not possible as minVersion.
So I think we only have two possible "solutions":

1.  Ditch the Android preference logic (I don't like that one, a lot of stuff e.g. the states, views, persistence of the settings is handled here)
2. Duplicate core settings into the shared preferences and sync them if needed (no perfect, but from my perspective the better approach)

What do you think @r10s ? I will think about a good and small wrapper approach for solution number 2.

**Comment by r10s** [comment]
@Boehrsi i will do the suggested change and close this issue then.

**Comment by Boehrsi** [comment]
@r10s great and and I'm glad that I could help. :)
