### ISSUE TITLE
remove unused permissions, delay requests

### ISSUE THREAD

**Issue by r10s** [deltachat/deltachat-android-ii#68]
we should cleanup the app from unused permissions as sms-sending.

moreover, rights should be requested in the moment they are really needed, eg. the right to write the sd-card should be requested when a file is about being exported, see #19

**Comment by Boehrsi** [comment]
Will tackle that one today.

**Comment by Boehrsi** [comment]
Should be fixed now.

**Comment by r10s** [comment]
looks good :)
