### ISSUE TITLE
send image messages

### ISSUE THREAD

**Issue by r10s** [deltachat/deltachat-android-ii#70]

**Comment by hpk42** [comment]
what is actually missing? I can  take/select a photo already but it's not ultimately send -- is a call into deltachat-core missing there or is it more involved?

**Comment by r10s** [comment]
nothing is missing, it's just not yet done :)

i think i will do this together with handling of complex-drafts, https://github.com/deltachat/deltachat-core/issues/214, however, this is not hard requirement.

**Comment by r10s** [comment]
closed by https://github.com/deltachat/deltachat-android-ii/commit/7bcfec2367435392d644f73b01a17fa292f885b7

**Comment by bokf** [comment]
How about image compression? Images are sent now with original size.

**Comment by r10s** [comment]
@bokf thanks for pointing this out, we had this in mind, however, i've filed a concrete issue at #168 now :)
