### ISSUE TITLE
add status/footer to "your profile" settings

### ISSUE THREAD

**Issue by r10s** [deltachat/deltachat-android-ii#76]
we forgot to add the status/footer setting to the "your profile" fragment.

the status/footer is a text that is added below each outgoing mail, it defaults to sth. as `Sent with my Delta Chat messenger`

for getting the text:

```
String statusText = dcContext.getConfig("selfstatus", null);
if( statusText == null ) {
 statusText = getString(R.string.default_status_text);
}
```

for setting the text:

```
String newstatus = statusCell.getValue().trim();
String defstatus = getString(R.string.default_status_text);
if( newstatus.equals(defstatus))  {
   dcContext.setConfig("selfstatus", null); // use default status, this allows us to change unmodified status lines
}
else {
  dcContext.setConfig("selfstatus", newstatus); // if v is empty, no status is send
}
```

**Comment by Boehrsi** [comment]
I will tackle this one together with a colleague who will probably also join the OX-Delta efforts. He is currently learning Android development and I think this is a good starting point.

**Comment by r10s** [comment]
cool :)

**Comment by r10s** [comment]
@Boehrsi when targeting this, can you also get/set the avatar image to the core? i think the ui is already there and the corresponding functions are dcContext.set/getConfig("selfavatar"), (just in core-queue :) - https://github.com/deltachat/deltachat-core/pull/341)

**Comment by Boehrsi** [comment]
Can get closed

**Comment by r10s** [comment]
great, no we only heave to spear the avatar in deltachat-core (the status text is already spreaded)

i think this can be closed :)
