### ISSUE TITLE
ask before deleting contacts

### ISSUE THREAD

**Issue by r10s** [deltachat/deltachat-android-ii#82]
similar to deleting chats and messages, the user should be asked before the contacts are deleted. 

this is useful mainly for internal consistence, however, the text can also explain in a few words that
- it is not possible to delete contacts that are in use
- it is not possible to delete contacts from the internal address book (they will be re-added unless permission to contacts is denied)

**Comment by r10s** [comment]
great :)

**Comment by Boehrsi** [comment]
Added the dialog and guessed a fix for the UI problem as I can't reproduce it.

**Comment by r10s** [comment]
great :)

>  guessed a fix for the UI problem as I can't reproduce it.

i will have a look at it and otherwise try it to fix on my own (it happens on my device, so probably it's easier :)

**Comment by r10s** [comment]
ok, i close this issue and the ui glitch lives on in #83
