### ISSUE TITLE
Set minSdkVersion to 19

### ISSUE THREAD

**Issue by Boehrsi** [deltachat/deltachat-android-ii#84]
As currently only 3.8% are below that mark and a lot of APIs are only usable on 19 or above I would highly suggest to update the minSdkVersion. Would that be fine for you @r10s?

**Comment by r10s** [comment]
i would not increase this without having a concrete reason :)

**Comment by r10s** [comment]
[](url)

**Comment by r10s** [comment]
sorry

**Comment by r10s** [comment]
> But there is a concrete reason ;)

i see :)

> some functions which are currently in the implementation phase require minSdkVersion to 19.

which are these functions?
and aren't there ways to use them only if they are available?

in general, i would like to postpone the decision of raising the min-requirements a bit until we have more concrete information about the read usage in our user group. 
i can imagine that these 3.8% can be much higher in some groups we may want to target.

**Comment by Boehrsi** [comment]
I will collect some examples on Monday. It's often possible to work around the minimum API requirements by manually creating some stuff, but this often leads to faulty re-implementations of existing stuff, which can be dangerous especially in the security area.
I totally understand that raising the minimum requirements is never "good" in regards the users, but sometime it should be done. I'm totally fine to keep it for the moment, until we have some insights in regards to our user base.

**Comment by r10s** [comment]
perfect :)

**Comment by Boehrsi** [comment]
Just some examples: 

- public void startActivity(Intent intent, Bundle options) API 16
- Manifest.permission.READ_EXTERNAL_STORAGE API 16
- Intent.ACTION_OPEN_DOCUMENT API 19
- WindowManager.LayoutParams.FLAG_TRANSLUCENT_STATUS API 19
- A general search for @TargetApi show how much "work arounds" are already in place. Not a problem per se and sometimes this is required, but this clutters the code and should get minimized

In general there are not critical ones for now I would say. I would say we can close this for now and after the user feedback / user test we have a look which Android version most of the users are using and if an update of the minSdkVersion could be fine. Okay for you @r10s ?

**Comment by r10s** [comment]
perfect, so we come back to this later. i'm fine with that. and thanks for the overview, this is very helpful :)

**Comment by r10s** [comment]
well, @angelo-fuchs has just fixed an issue for pre-lollipop, however, apart from that it seems to work, maybe with hacky-workarounds here and there, but, anyway.

some compromises will be needed, however. eg. upcoming features as video recoding (#165), won't be supported by SDK<18 as supporting these version seems to require adding and maintaining a bunch of c-libraries,.

in summary, wrt cuba and ukraine but also for installing on cheap phones in general, i have the feeling that it's worth keeping the current state, for a while. also as there is not much do do _currently_.

cc @adbenitez

**Comment by adbenitez** [comment]
While spreading DC I have found only one user that was using an Android version not even supported for Delta Chat v0.20. My personal opinion in this matter is that it is better the speed and reach on the user base, than removing support in favour of superfluous features or "fancy" UIs. 
But even here in Cuba, I think most users have Android > API 19, as example I am pretty poor, my phone has less than 500MB of RAM but comes with API 23 (6.0)

**Comment by r10s** [comment]
thanks, these are very useful information, indeed :)
