### ISSUE TITLE
Adjust the CreateProfileActivity UI

### ISSUE THREAD

**Issue by Boehrsi** [deltachat/deltachat-android-ii#87]
We should adjust the UI to the default patterns used within the app. 

- "x" icon as up icon
- "check mark" icon at the right top should replace the current "finish" button
- The current "finish" animation should stay
- A multi line input view should be used for the status text input

**Comment by r10s** [comment]
@florianhaar great job :) much better now, esp. the multi-line input was really needed :)

some nitpicking from my side:
- can we have a little more space between the avatar and the status input field? currently, the "Status text" headline looks like it belongs to the avatar. 
- maybe we can show the title of the name fields also if a name is entered
- i would remove the keyboard-smiley-toggle-button beside the name
- i would show the last link "password and account settings" in the same font+color as the "who can use these information" link. but it's fine if it is aligned to the bottom, i would really just change the font+color :)

**Comment by r10s** [comment]
@florianhaar perfect :)

i think, sooner or later we should also open an issue to move the "Login" button of the RegistrationActivity the same way, however, this is another issue and this one can be closed :)
