### ISSUE TITLE
Updatet to 0.0.3; still shows v0.0.2 in Settings

### ISSUE THREAD

**Issue by violoncelloch** [deltachat/deltachat-android-ii#89]
updated to dev 0.0.3, but dc settings still show 0.0.2
Is this a problem of dc or did my instance not update correctly?

**Comment by r10s** [comment]
it was my fault: forgot to increase the internal version number, sorry.

**Comment by violoncelloch** [comment]
Ok, thank you

**Comment by r10s** [comment]
that you for the hint. i'll try to be more careful the next time :)
