### ISSUE TITLE
what is a good way to access ApplicationDcContext?

### ISSUE THREAD

**Issue by r10s** [deltachat/deltachat-android-ii#9]
ApplicationContext.getInstance(getApplicationContext()).dcContext seems to be a little painful.

(used this way eg. in RegistrationActivity)

**Comment by Boehrsi** [comment]
Will have a look into this, there should be a prettier way. But we could at least refactor such calls into Base* classes, as this will be used in any class aware of the core.

**Comment by Boehrsi** [comment]
I just tried something in https://github.com/deltachat/deltachat-android-ii/commit/8e9f398e491347186b0496ac6c6adad4514d9642 and created a small wrapper https://github.com/deltachat/deltachat-android-ii/commit/8e9f398e491347186b0496ac6c6adad4514d9642#diff-dd4d2b1da1d3b500a1f3e31f2f98ae90 we can extend / rename or whatsoever.

**Comment by Boehrsi** [comment]
Sure, it will adjust that during my work on https://github.com/deltachat/deltachat-android-ii/issues/14 as I think I will create more "easy access methods" anyway within that helper class.

**Comment by r10s** [comment]
or `DcHelper.getContext()` - then other "easy access methods" would also make sense when they're not strictly related to DcContext - but eg. to events or whatever. also we would avoid a very generic get() method name while still  being short.

**Comment by Boehrsi** [comment]
Yep that's true, will go the DcHelper.* way  :+1:

**Comment by r10s** [comment]
cool :)
