### ISSUE TITLE
edit groups

### ISSUE THREAD

**Issue by r10s** [deltachat/deltachat-android-ii#92]
editing groups means:
- adding and removing members
- changing the group name
- changing the group image

for all of these actions, a chatId is needed and the corresponding functions are DcContext.addContactToChat(), DcContext.removeContactToChat(), DcContext.setChatName() and DcContext.setChatProfileImage()

the ui for all these functions can be the same as for creating a group, GroupCreateActivity - the comment from the signal code gives a hint that it was used the same way there ("Activity to create and update groups" :)

i would suggest to make the user edit the list, name and icon and only _if_ the user clicks the ok-checkbox on the upper-right corner, the action is really done.

the group-edit should be started by clicking on the group-icon in the upper right area of the ConversationActivity's action bar.

**Comment by Boehrsi** [comment]
Will tackle that one, starting now.

**Comment by Boehrsi** [comment]
Extended our _DcContact / DcChat to Signal models_ flow and added the form prefill for group editing. The actual actions should follow tomorrow.

**Comment by r10s** [comment]
btw. there is an outdated comment in ConversationActicity.handleDisplayGroupRecipients() that says, profile should be used.

i think, for now, we should just use exactly this button for editing groups :)

**Comment by Boehrsi** [comment]
A lot of distractions / meetings / other projects, so no real progress here :-1: . Will continue next week, as the next meeting already approaches.

**Comment by r10s** [comment]
okay, cu next week then :)

**Comment by r10s** [comment]
just a little note:
currently, the action-bar-title of the "New group" and "New verified group" is always "Edit group".

**Comment by r10s** [comment]
> EDIT: it's not just the title, creating groups just does no longer works ;)

fixed this.

**Comment by r10s** [comment]
great :)

i first did not found it as i was always clicking on the group-icon :)
i would suggest to move "edit group" there; i do not think there is a need for an extra recipient list

one minor thing: 
when the edit-group activity is opened, the group name is focused and the keyboard appears.
while this makes sense when creating a group (and should not be changed there) i would not open the keyboard by default for editing groups as it hides the member list.

everything else looks good to me :)

**Comment by r10s** [comment]
'edit group' can be opened by the icon now (ifRoom :)

**Comment by Boehrsi** [comment]
Ah sorry overread that requirement :/.

**Comment by r10s** [comment]
no problem :)

**Comment by Boehrsi** [comment]
> great :)
> 
> i first did not found it as i was always clicking on the group-icon :)
> 
>     * [x]  i would suggest to move "edit group" there; i do not think there is a need for an extra recipient list
> 
>     * [x]  one minor thing:
>       when the edit-group activity is opened, the group name is focused and the keyboard appears.
>       while this makes sense when creating a group (and should not be changed there) i would not open the keyboard by default for editing groups as it hides the member list.
> 
> 
> everything else looks good to me :)

Adjusted the keyboard state, so this ticket should be ready. Will switch to avatars #55 now, so the edit function for group avatars is actually visible.

**Comment by r10s** [comment]
@Boehrsi great :)

one thing i just encountered: when editing a group, the "show qr veryify code" button is not available.

it should be there and show the qr-code generated from getSecurejoinQr() with a set chat_id then. this should work by opening the QrShowActivity with the extra chat_id set.

also, we should to check if the list of contacts is updated on contacts added this way. might be already the case, not sure.

finally, i think one self should be in the list as well, not sure why it is not there, getChatContacts() should return SELF as well.
if think it is also fine to show SELF when creating a group, so, we can show SELF just always in the list.

**Comment by Boehrsi** [comment]
@r10s will look into the remaining tasks tomorrow. The self reference is filtered out explicitly, as it's also not there when creating a group. I'm not sure if everything works well if one removes the self reference.

**Comment by r10s** [comment]
> I'm not sure if everything works well if one removes the self reference.

this is no problem, it's just the same as leaving the group.

**Comment by Boehrsi** [comment]
- [x] Add qr button on verify edit 
- [x] Show qr code for the selected group
- [x] Show "ME" and allow to remove "ME"
- [ ] Automatically remove the group if "ME" leaves
- [ ] Check for list update on QR join

**Comment by Boehrsi** [comment]
@r10s calling dcContext.deleteChat() on chats where I left makes sense right?

**Comment by r10s** [comment]
@Boehrsi i would treat leaving a chat and deleting a chat as two independent actions.

leave only: maybe you do not want to get more messages in a chat, but keep/archive the existant onces.

delete only: deleting a chat is just the opposite from creating it. new messages for the chat will arrive.

it may make sense, however, to ask the user on deletion whether he also want to leave a chat.

**Comment by hpk42** [comment]
On Tue, Oct 30, 2018 at 08:42 -0700, björn petersen wrote:
> @Boehrsi i would treat leaving a chat and deleting a chat as two independent actions.
> 
> leave only: maybe you do not want to get more messages in a chat, but keep/archive the existant onces.
> 
> delete only: deleting a chat is just the opposite from creating it. new messages for the chat will arrive.
> 
> it may make sense, however, to ask the user on deletion whether he also want to leave a chat. but this is not really related to "Edit group"

FWIW it sounds to me like "delete chat" really means "delete chat messages" here.
if i select "delete chat messages" i would not be surprised to see new messages 
arrive afterwards.  So maybe it's also a matter of wording in the UI?

**Comment by r10s** [comment]
yes, improving the wording will probably make the options much clearer.

however in fact it would be "Delete messages" sounds more like "Empty view" to me -  so i would not really expect the chat being removed from the chatlist.
otoh it's probably better than "Delete chat" in this case :)

**Comment by Boehrsi** [comment]
@r10s okay :), I will just keep the open chat then. Additional wording / UI stuff should probably be done in another ticket or after some initial testing.

**Comment by Boehrsi** [comment]
Added the remaining verify logic. So the general edit group functionality should be ready now.

**Comment by r10s** [comment]
cool :)

**Comment by r10s** [comment]
@Boehrsi looks good to me, great :)

the next step is to integrate the edit-group-screen to the common profile view (but this needs some syncing, also with @angelo-fuchs who did the media overview) and to use the "normal" controls in the list, #48 

however, these are the next issues then and this can be closed for now :)
