### ISSUE TITLE
Verify icon layout broken

### ISSUE THREAD

**Issue by r10s** [deltachat/deltachat-android-ii#93]
not sure which, but one of the last commits has mixed up the verification icon layout. 

- in the ConversationActivity (ConversationTitleView) the verified-icon is is shown very small, i am pretty sure this was correct some days ago
- the width of the title is limited by the width of the subtitle (eg. "A longer group name" is truncated as the subtitle is shorter ("2 members")) - not sure if this was different before, anyway
- the ConverstationList the verified-icon is right-aligned where it should just be placed after the title.

might come from this commit, https://github.com/deltachat/deltachat-android-ii/commit/bf85918ed2d7694b2967262e081fdc64ff521ccb, as this has changed both, conversation_title_view.xml as well as conversation_list_item_view.xml)

@Boehrsi can you please have a loot at this? i am pretty sure you have much better insights there :)

**Comment by Boehrsi** [comment]
Will have a look. I'm pretty sure the last commit broke it. The problem is that the layout structure there is pretty annoying. Aligning the item right to the text worked before, but if the group name is longer than the screen the verify icon is pushed out of the screen. I tried to fix that with the last commit, but it seems it didn't worked out. Will tackle that now.

**Comment by Boehrsi** [comment]
The issue should now be fixed, but the verify icon will always be aligned to the right inside the parent, not beside the group name / user name. Using the current UI this is a limitation. Another approach would be putting the verify icon to the left of the group name / user name but I think this is fine for the moment.

**Comment by r10s** [comment]
great, looks very good now :)

to right-align the verifiy-icon just right of the text, i am wondering if we cannot use just setCompoundDrawablesWithIntrinsicBounds(). 
Currently, it's unused in ConversationTitleView.setTitle(), but even if we add "mute" to the left, the right one is free :)
however, for now, this is not the most important part and this issue is closed :)

**Comment by Boehrsi** [comment]
Great @r10s :) and yes the setCompoundDrawablesWithIntrinsicBounds could get used for one case (already tried this while working in that area) but the other one already uses images bound by setCompoundDrawablesWithIntrinsicBounds on the right of the text as far as I saw. We could think about some general UI adjustments / clean ups to fix that problem completely.
