### ISSUE TITLE
Chats aren't getting synced

### ISSUE THREAD

**Issue by Jikstra** [deltachat/deltachat-android-ii#94]
**Delta Chat version**

0.0.6

**Expected behavior**

- Chats from desktop/mobile getting retrieved on newly activated/synced device

**Actual behavior**

- No synced/old chats :(

**Steps to reproduce the problem**

1. …
2. …

**Screen snapshots**

**Debug logs**
<details>
<summary>Logs</summary>

```

<!--
If applicable, debug logs can be copied from within the Delta Chat app: 

Open the _Settings_ menu -> _About_ -> _version number|Info_.

Alternatively from the Android system log:

` adb logcat -v time -s DeltaChat `

This log contains private data (e.g. mail address, provider information) which shall be removed or anonymised prior to posting.
-->

```
</details>

**Comment by r10s** [comment]
hi @Jikstra -

yes, _chats_ are not synchronized by the core currently, only _messages_ as follows:

- outgoing messages should be synchronized completely after ~30 minutes.
- incoming messages should pop up at once on all devices

these synchronized messages may create a chat then, it depends on whether the contact is know.

to improve this, a first step is our single-folder approach https://github.com/deltachat/deltachat-core/milestone/2

if this is implemented, incoming and outgoing messages should be synced at once; and this is a good platform for further iterations then.

however, finally, i am not sure if _this_ issue is really android-dev or delta-desktop related; maybe we should close it here and continue the discussion in one of the linked issues related to deltachat-core.

**Comment by Jikstra** [comment]
Okay didn't know that but makes sense. Let's discuss this on deltachat-core, maybe even a deltachat-meta repo or something to discuss cross platform behaviour. Let's get this closed :)
