### ISSUE TITLE
right align lock/time/deliveryInfo in images

### ISSUE THREAD

**Issue by r10s** [deltachat/deltachat-android-ii#99]
lock/time/deliveryInfo are right aligned in normal messages, so they should be in images.

**Comment by florianhaar** [comment]
@r10s will start with this one now

**Comment by florianhaar** [comment]
@r10s should be as expected

**Comment by r10s** [comment]
great that you push this forward and figure out the correct line to change.
however, wrt to right-to-left-languages, shouldn't it read `bottom|right|end` or just `bottom|end`?

what i've seen for the other footer controls, they add `end` here.

**Comment by florianhaar** [comment]
@r10s you are right and I fixed this :)

**Comment by r10s** [comment]
@florianhaar thank you very much for confirmation and for fixing. we can close this now.
